### ISSUE TITLE
py-macaroon-bakery & pymacaroons depend on completely different implementation of nacl

### ISSUE THREAD

**Issue by roaksoax** [go-macaroon-bakery/py-macaroon-bakery#47]
py-macaroon-bakery depends on https://github.com/pyca/pynacl/
pymacaroons depends on https://github.com/saltstack/libnacl

Since both are related to each other, it would be nice if they share the same dependency and not completely different implementations

https://github.com/ecordell/pymacaroons/issues/44

**Comment by rogpeppe** [comment]
Interesting. Do you have an idea of which one might be preferable. Ideally we'd not depend on any C code FWIW.

**Comment by roaksoax** [comment]
Honestly, I do not know which library would be the best to be set on. I would recommend asking the security team to see if they prefer either one of those. Both upstream's seem to be active as well.

**Comment by johnsca** [comment]
FWIW, libnacl seems to cause [issues](https://readthedocs.org/projects/pythonlibjuju/builds/6776563/) with building docs on RTD due to the missing `libsodium.so` and their own docs hosted there haven't been updated for several releases.  pynacl appears to have some logic in its `setup.py` to build the necessary headers and their RTD builds are working fine.

**Comment by cjwatson** [comment]
pymacaroons has switched to pynacl (and the patch was surprisingly-to-me not terribly complex), so I guess this can be closed?
